# Site settings
title: Polkadotters
description: "Static website for Polkadotters community"
baseurl: "/"
url: "https://www.polkadotters.com" # the base hostname & protocol for your site
author: Petr Mensik
lang: cs_CZ

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
